services:
  mod-ios:
    build: .
    image: mod-ios
    container_name: mod-ios-mod-ios-1
    volumes:
      - ./data:/data
      - ./reports:/app/reports
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
