name: Extension CI

on:
  push:
    paths:
      - 'vscode-extension/**'
  pull_request:
    paths:
      - 'vscode-extension/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps
        run: npm install
      - name: Compile extension
        run: npm run compile
      - name: VSCE package
        run: |
          npm install -g vsce
          vsce package
